# NumPy基础操作

### 创建向量：创建一维数组


In [6]:
import numpy as np
from mpmath import matrix

#行形式创建向量
vetor_row=np.array([1,2,3])
#将向量创建为列
vetor_column=np.array([[1],
                       [2],
                       [3]])

### 创建矩阵：创建二维数组


In [ ]:
import numpy as np

matrix=np.array([[1,2],
                 [1,2],
                 [1,2]])

### 创建稀疏矩阵：非零值极少时

In [9]:
import numpy as np
from scipy import sparse

#创建矩阵
matrix=np.array([[0,0],
                 [0,1],
                 [3,0]])
#创建压缩系数行矩阵
matrix_sparse=sparse.csr_matrix(matrix)
print(matrix_sparse)
#创建更大的矩阵
matrix_large=np.array([[0,0,0,0,0,0,0,0,0,0],
                        [0,1,0,0,0,0,0,0,0,0],
                        [3,0,0,0,0,0,0,0,0,0]])
#create compressed sparse row(CSR) matrix
matrix_large_sparse=sparse.csr_matrix(matrix_large)

#查看原始稀疏矩阵
print(matrix_sparse)

#查看更大的稀疏矩阵
print(matrix_large_sparse)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 10)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3


(1,1)表示非零值 1 的位置，第二行第二列

同理，另一个表示 3

### 预分配 NumPy 数组


问题：您需要预先分配指定大小并赋值的数组

解决：NumPy 提供了使用 0、1 或自定义数值生成任意大小向量和矩阵的功能：

In [11]:
import numpy as np

#生成一个形状为（1，5）的向量，其中所有元素均为零
vector=np.zeros(shape=5)
print(vector)

#生成一个形状为（3,3）的向量，其中所有元素均为1
matrix=np.full(shape=(3,3),fill_value=1)
print(matrix)

[0. 0. 0. 0. 0.]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


### 选择元素

- 问题：您需要在向量或矩阵中选择一个或多个元素。
- 解决：

In [12]:
import numpy as np

#创建行向量
vector=np.array([1,2,3,4,5,6])

In [13]:

#创建矩阵
matrix=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
#选择向量的第三个元素

In [15]:
print(vector[2])

#选择第二行第二列
print(matrix[1,1])

3
5


NumPy数组采用零索引方式，即第一个元素的索引为0而非1

NumPy提供了多种用于选择数组中单个元素或元素组的方法（包括索引访问和切片操作）

In [27]:
import numpy as np

#创建行向量
vector = np.array([1, 2, 3, 4, 5, 6])

#创建矩阵
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
#选择向量中的所有元素
print(f"向量中所有元素为{vector[:]}")
#选择包含第三个元素在内的所有内容
print(f"向量中包含第三个元素在内的所有内容为{vector[:3]}")
# 选择第三个元素之后的所有内容
print(f"向量中包含第三个元素之后的所有内容为{vector[3:]}")
#最后一个元素
print(f"最后一个元素为{vector[-1]}")
#反转向量
print(f"反转向量后为{vector[::-1]}")

#选择矩阵的前两行及所有列
print(f"矩阵的前两行及所有列为{matrix[:2,:]}")
matrix[:2,:]
#选中所有行及第二列
print(f"矩阵的所有行及第二列为{matrix[:,1:2]}")
matrix[:,1:2]

向量中所有元素为[1 2 3 4 5 6]
向量中包含第三个元素在内的所有内容为[1 2 3]
向量中包含第三个元素之后的所有内容为[4 5 6]
最后一个元素为6
反转向量后为[6 5 4 3 2 1]
矩阵的前两行及所有列为[[1 2 3]
 [4 5 6]]
矩阵的所有行及第二列为[[2]
 [5]
 [8]]


array([[2],
       [5],
       [8]])

### 描述一个矩阵

- 问题：You want to describe the shape, size, and dimensions of a matrix.
- 解决：

In [1]:
import numpy as np

matrix=np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])
#查看行数和列数
print(f"行数和列数为{matrix.shape}")
#查看元素数量
print(f"元素数量为{matrix.size}")
#查看维度
print(f"维度为{matrix.ndim}")

行数和列数为(3, 4)
元素数量为12
维度为2
