# NumPy基础操作

### 创建向量：创建一维数组


In [6]:
import numpy as np   导入numpy为np
from mpmath import matrix

#行形式创建向量
vetor_row=np.array([1,2,3])
#将向量创建为列
vetor_column=np.array([[1],
                       [2],
                       [3]])

### 创建矩阵：创建二维数组


In [ ]:
import numpy as np   导入numpy为np

matrix=np.array([[1,2],
                 [1,2],
                 [1,2]])

### 创建稀疏矩阵：非零值极少时

In [9]:
import numpy as np   导入numpy为np
from scipy import sparse

#创建矩阵
matrix=np.array([[0,0],
                 [0,1],
                 [3,0]])
#创建压缩系数行矩阵
matrix_sparse=sparse.csr_matrix(matrix)
print(matrix_sparse)
#创建更大的矩阵
matrix_large=np.array([[0,0,0,0,0,0,0,0,0,0],
                        [0,1,0,0,0,0,0,0,0,0],
                        [3,0,0,0,0,0,0,0,0,0]])
#create compressed sparse row(CSR) matrix
matrix_large_sparse=sparse.csr_matrix(matrix_large)

#查看原始稀疏矩阵
print(matrix_sparse)

#查看更大的稀疏矩阵
print(matrix_large_sparse)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 10)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3


(1,1)表示非零值 1 的位置，第二行第二列

同理，另一个表示 3

### 预分配 NumPy 数组


问题：您需要预先分配指定大小并赋值的数组

解决：NumPy 提供了使用 0、1 或自定义数值生成任意大小向量和矩阵的功能：

In [11]:
import numpy as np

#生成一个形状为（1，5）的向量，其中所有元素均为零
vector=np.zeros(shape=5)
print(vector)

#生成一个形状为（3,3）的向量，其中所有元素均为1
matrix=np.full(shape=(3,3),fill_value=1)
print(matrix)

[0. 0. 0. 0. 0.]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


### 选择元素

- 问题：您需要在向量或矩阵中选择一个或多个元素。
- 解决：

In [12]:
import numpy as np

#创建行向量
vector=np.array([1,2,3,4,5,6])

In [13]:

#创建矩阵
matrix=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
#选择向量的第三个元素

In [15]:
print(vector[2])

#选择第二行第二列
print(matrix[1,1])

3
5


NumPy数组采用零索引方式，即第一个元素的索引为0而非1

NumPy提供了多种用于选择数组中单个元素或元素组的方法（包括索引访问和切片操作）

In [4]:
import numpy as np

#创建行向量
vector = np.array([1, 2, 3, 4, 5, 6])

#创建矩阵
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
#选择向量中的所有元素
print(f"向量中所有元素为{vector[:]}")
#选择包含第三个元素在内的所有内容
print(f"向量中包含第三个元素在内的所有内容为{vector[:3]}")
# 选择第三个元素之后的所有内容
print(f"向量中包含第三个元素之后的所有内容为{vector[3:]}")
#最后一个元素
print(f"最后一个元素为{vector[-1]}")
#反转向量
print(f"反转向量后为{vector[::-1]}")

#选择矩阵的前两行及所有列
print(f"矩阵的前两行及所有列为{matrix[:2,:]}")
matrix[:2,:]
#选中所有行及第二列
print(f"矩阵的所有行及第二列为{matrix[:,1:2]}")
matrix[:,1:2]

向量中所有元素为[1 2 3 4 5 6]
向量中包含第三个元素在内的所有内容为[1 2 3]
向量中包含第三个元素之后的所有内容为[4 5 6]
最后一个元素为6
反转向量后为[6 5 4 3 2 1]
矩阵的前两行及所有列为[[1 2 3]
 [4 5 6]]
矩阵的所有行及第二列为[[2]
 [5]
 [8]]


array([[2],
       [5],
       [8]])

### 描述一个矩阵

- 问题：You want to describe the shape, size, and dimensions of a matrix.
- 解决：

In [2]:
import numpy as np

matrix=np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])
#查看行数和列数
print(f"行数和列数为{matrix.shape}")
#查看元素数量
print(f"元素数量为{matrix.size}")
#查看维度
print(f"维度为{matrix.ndim}")

行数和列数为(3, 4)
元素数量为12
维度为2


### 对每个元素应用函数

- 问题：您希望对数组中的所有元素应用某个函数。
- 解决：NumPy的向量化方法

In [5]:
import numpy as np
#创建矩阵
matrix=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
#创建一个可将数值加100的功能函数
add_100=lambda i:i+100
#创建向量化函数
vectorized_add_100=np.vectorize(add_100)
#对矩阵中的所有元素应用函数
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

NumPy的**vectorize**方法可将函数转换为适用于数组或数组切片中所有元素的函数。需要特别说明的是，vectorize本质上是对元素执行for循环操作，并不会提升性能。

####  broadcasting

In [6]:
import numpy as np
#创建矩阵
matrix=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
#在所有元素中添加100
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

Broadcasting does not work for all shapes and situations, but it is a common way of applying simple operations over all elements of a NumPy array.

### 求最大值和最小值

- 问题：您希望求数组中所有元素的最大值或最小值。
- 解决：NumPy的**max**和**min**方法


In [7]:
import numpy as np

#创建矩阵
matrix=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
#返回最大元素
print(f"最大元素为{np.max(matrix)}")
#返回最小元素
print(f"最小元素为{np.min(matrix)}")

最大元素为9
最小元素为1


通过使用axis参数，我们还可以沿特定轴方向执行该操作：

In [13]:
import numpy as np

#创建矩阵
matrix=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
#在每列中查找最大值
print(f"每列的最大值为{np.max(matrix,axis=0)}")
#在每行中查找最大值
print(f"每行的最大值为{np.max(matrix,axis=1)}")

每列的最大值为[7 8 9]
每行的最大值为[3 6 9]


### 计算平均值、方差和标准差

- 问题：您需要计算数组的相关描述性统计量。
- 解决：NumPy的**mean**、**var**和**std**方法


In [14]:
import numpy as np
#创建矩阵
matrix=np.array([[1,2,3],
                 [4,5,6],
                [7,8,9]])
#返回平均值
print(f"平均值为{np.mean(matrix)}")
#回归方差
print(f"方差为{np.var(matrix)}")
#返回标准差
print(f"标准差为{np.std(matrix)}")


平均值为5.0
方差为6.666666666666667
标准差为2.581988897471611


与max和min类似，我们可以轻松获取整个矩阵的描述性统计量或沿单个轴进行计算：

In [ ]:
import numpy as np
#创建矩阵
matrix=np.array([[1,2,3],
                 [4,5,6],
                [7,8,9]])
#在每列中查找平均值
np.mean(matrix,axis=0)

### 重塑数组

- 问题：修改数组结构但不改变元素值
- 解决：NumPy的**reshape**方法

In [15]:
import numpy as np

#create 4*3 matrix
matrix=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9],
                 [10,11,12]])
#将矩阵转换为（reshape）为2*6矩阵
matrix.reshape(2,6)


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

reshape函数允许我们重组数组结构，同时保持原有数据不变，但将其组织为不同数量的行和列。唯一要求是**原始矩阵与新矩阵的形状必须包含相同数量的元素**（即大小一致）

- 查看矩阵大小：size

In [19]:
matrix.size

12

reshape函数中的一个有用参数是-1，其实际含义为“按需添加”，

因此reshape(1，-1)表示生成一行数据及所需数量的列：(矩阵)

In [20]:
matrix.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

最后，如果我们提供一个整数，reshape函数将返回一个长度为该整数的<mark>一维数组</mark>：

In [21]:
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### 转置向量或矩阵

- 问题：对向量或矩阵进行转置操作
- 解决：NumPy的**T**属性


In [22]:
import numpy as np
matrix=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
#转置矩阵
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

向量本身无法被转置，因为它仅仅是一组数值的集合：

In [24]:
#转置向量
np.array([1,2,3,4,5,6]).T

array([1, 2, 3, 4, 5, 6])

然而，通常将向量转置称为将行向量转换为列向量（注意有第二对中括号），反之亦然。

In [25]:
#转置行向量
np.array([[1,2,3,4,5,6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

### Flattening a Matrix


- 问题：将矩阵转换为一维数组
- 解决：NumPy的**flatten**方法

In [26]:
import numpy as np
matrix=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
#flatten矩阵
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

使用**reshape**来创建行向量：

In [27]:
matrix.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

另一种常见的数组展平方法是**ravel方法**。**ravel**直接作用于原始对象本身，因此速度略快。该方法还能实现对**数组列表**的展平操作——这是flatten方法无法做到的。此操作特别适用于展平**超大规模数组**并加速代码执行：

In [28]:
#创建第一个矩阵
matrix_a=np.array([[1,2],
                   [3,4]])
#创建第二个
matrix_b=np.array([[5,6],
                   [7,8]])
#创建矩阵列表
matrix_list=[matrix_a,matrix_b]
#Flatten 整个矩阵列表
np.ravel(matrix_list)

array([1, 2, 3, 4, 5, 6, 7, 8])

### 求矩阵的秩

- 问题：您需要计算矩阵的秩。
- 解决：**matrix_rank**方法


In [29]:
import numpy as np
matrix=np.array([[1,1,1],
                 [1,1,10],
                 [1,1,15]])
# Return matrix rank
np.linalg.matrix_rank(matrix)

np.int64(2)

矩阵的秩是指由其列或行张成的向量空间的维度

### 求矩阵的对角线元素

- 问题：获取矩阵的对角元素
- 解决：**diagonal**方法


In [30]:
import numpy as np
matrix=np.array([[1,2,3],
                 [2,4,6],
                 [3,8,9]])
# Return diagonal elements
matrix.diagonal()

array([1, 4, 9])

还可使用**offset**参数获取主对角线以外的对角元素：


In [31]:
#  Return diagonal one above the main diagonal【主对角线线上方的对角元素】
matrix.diagonal(offset=1)

array([2, 6])

In [32]:
#  Return diagonal one below the main diagonal【主对角线线下方的对角元素】
matrix.diagonal(offset=-1)

array([2, 8])

### 计算矩阵的迹


- 问题：您需要计算矩阵的迹。
- 解决：**trace**方法

In [34]:
import numpy as np
matrix=np.array([[1,2,3],
                  [2,4,6],
                  [3,8,9]])
# Return matrix trace
matrix.trace()#1+4+9=14

np.int64(14)

直接获取矩阵的对角线元素并求其总和:

In [35]:
# Return diagonal and sum elements
sum(matrix.diagonal())

np.int64(14)

### 计算点积

- 问题：您需要计算向量或矩阵的点积。
- 解决：**dot**方法


In [37]:
import numpy as np
vector_a=np.array([1,2,3])
vector_b=np.array([4,5,6])
# Calculate dot product
np.dot(vector_a,vector_b)#1*4+2*5+3*6=32

np.int64(32)

在 Python 3.5 及更高版本中，可使用新的 @ 运算符：

In [39]:
vector_a @ vector_b

np.int64(32)

### 矩阵的加法与减法

- 问题：您需要对两个矩阵进行加法或减法操作。
- 解决： NumPy’s add and subtract:

In [40]:
import numpy as np
matrix_a=np.array([[1,1,1],
                 [1,1,1],
                 [1,1,2]])
matrix_b=np.array([[1,3,1],
                   [1,3,1],
                   [1,3,8]])
# Add two matrices
np.add(matrix_a,matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [41]:
# Subtract two matrices
np.subtract(matrix_a,matrix_b)


array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

 we can simply use the + and – operators:

In [42]:
# Add two matrices
matrix_a+matrix_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

### 矩阵乘法

NumPy’s dot:

In [43]:
import numpy as np
matrix_a=np.array([[1,1],
                   [1,2]])
matrix_b=np.array([[1,3],
                   [1,2]])
# Multiply two matrices
np.dot(matrix_a,matrix_b)

array([[2, 5],
       [3, 7]])

在 Python 3.5 及更高版本中，我们可以使用 @ 运算符：

In [44]:
matrix_a @ matrix_b


array([[2, 5],
       [3, 7]])

若需进行元素级乘法运算，可使用*运算符：【即对应位置元素进行相乘】

In [45]:
# Multiply two matrices element-wise
matrix_a * matrix_b

array([[1, 3],
       [1, 4]])

### 矩阵求逆

- 问题：方阵的逆矩阵
- 解决：NumPy’s **linear algebra inv** method:


In [46]:
import numpy as np
matrix=np.array([[1,4],
                 [2,5]])
# Calculate inverse of matrix
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

将矩阵与其逆矩阵相乘，结果即为单位矩阵：

In [47]:
matrix @ np.linalg.inv(matrix)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

### 生成随机值

NumPy’s random:

In [48]:
import numpy as np
#set seed
np.random.seed(0)

# 在 0.0 到 1.0 之间生成三个随机浮点数
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

生成整数:

In [49]:
# 在 0 到 10 的范围内生成三个随机整数
np.random.randint(0,11,3)

array([3, 7, 9], dtype=int32)

或者，我们也可以通过从某个分布中抽取数值来生成数字（需注意这在技术上并不属于随机抽样）。

In [50]:
# 从均值为 0.0、标准差为 1.0 的正态分布中抽取 3 个数
np.random.normal(0.0,1.0,3)

array([-1.42232584,  1.52006949, -0.29139398])

In [51]:
# 从均值(mean)为 0.0、规模（scale）为 1.0 的logistic distribution 中抽取 3 个数
np.random.logistic(0.0,1.0,3)

array([-0.98118713, -0.08939902,  1.46416405])

In [52]:
# 抽取 3 个大于等于 1.0 且小于 2.0 的数
np.random.uniform(1.0,2.0,3)

array([1.47997717, 1.3927848 , 1.83607876])